### ISSUE TITLE
recommend basing off 'safe' code

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [afsc-assessments/ssmesa-weekly#4]
https://github.com/afsc-assessments/ssmesa-weekly/blob/da845a7995fcada097bc2eaea1dbd34e45fd3d52/proj-example-goarebs/functions4proj.R#L404

safe package code is (much) more recent than the code you based this off - i haven't checked the old code in some time (i just archived that repo)  - better place to pull from is here https://github.com/BenWilliams-NOAA/safe/blob/main/R/main_table.R

**Comment by JaneSullivan-NOAA** [comment]
great thanks!
